// Exports sub-view: artifact downloads (VTU bundle, forces CSV, the Phase-0
// validation report generated by the harness) and the raw artifact list.

import { useEffect, useState } from 'react'

import {
  artifactUrl,
  bundleZipUrl,
  forcesCsvUrl,
  generateReport,
  type ArtifactInfo,
} from '../../api'
import { apiPath } from '../../config'

async function listArtifacts(runId: string): Promise<ArtifactInfo[]> {
  const response = await fetch(apiPath(`/api/runs/${runId}/artifacts`))
  if (!response.ok) return []
  const body = (await response.json()) as { artifacts: ArtifactInfo[] }
  return body.artifacts
}

export function ExportsView({ runId }: { runId: string }) {
  const [artifacts, setArtifacts] = useState<ArtifactInfo[]>([])
  const [reportState, setReportState] = useState<'idle' | 'generating' | 'ready' | 'error'>('idle')
  const [reportError, setReportError] = useState('')

  const refresh = () => void listArtifacts(runId).then(setArtifacts)
  useEffect(refresh, [runId])

  const hasReport = artifacts.some((a) => a.name === 'report.html')

  const makeReport = async () => {
    setReportState('generating')
    try {
      await generateReport(runId)
      setReportState('ready')
      refresh()
    } catch (err) {
      setReportError(err instanceof Error ? err.message : String(err))
      setReportState('error')
    }
  }

  return (
    <div className="post-view exports-view">
      <div className="export-cards">
        <div className="sim-panel export-card">
          <h4>VTU bundle</h4>
          <p className="muted">All snapshots + meshes, zipped for ParaView.</p>
          <a className="btn btn--primary" href={bundleZipUrl(runId, '.vtu')} download>
            Download .vtu bundle
          </a>
        </div>
        <div className="sim-panel export-card">
          <h4>Forces & metrics CSV</h4>
          <p className="muted">Per-step Cd, Cl, F_D, F_L, residuals, cell counts.</p>
          <a className="btn btn--primary" href={forcesCsvUrl(runId)} download>
            Download forces.csv
          </a>
        </div>
        <div className="sim-panel export-card">
          <h4>Phase-0 validation report</h4>
          <p className="muted">
            Generated by the validation harness — open and print to PDF.
          </p>
          {hasReport || reportState === 'ready' ? (
            <a
              className="btn btn--primary"
              href={artifactUrl(runId, 'report.html')}
              target="_blank"
              rel="noreferrer"
            >
              Open report
            </a>
          ) : (
            <button
              type="button"
              className="btn btn--primary"
              disabled={reportState === 'generating'}
              onClick={() => void makeReport()}
            >
              {reportState === 'generating' ? 'Generating…' : 'Generate report'}
            </button>
          )}
          {reportState === 'error' && <p className="muted">failed: {reportError}</p>}
        </div>
      </div>

      <div className="sim-panel">
        <h4>All artifacts</h4>
        <ul className="artifact-list">
          {artifacts.map((artifact) => (
            <li key={artifact.name}>
              <a href={artifactUrl(runId, artifact.name)} download>
                {artifact.name}
              </a>
              <span className="muted">{(artifact.size / 1024).toFixed(1)} KiB</span>
            </li>
          ))}
        </ul>
      </div>
    </div>
  )
}
